import { render, screen } from "@testing-library/react";
import "@testing-library/jest-dom";
import RootLayout, { metadata } from "./layout";

describe("RootLayout", () => {
  test("RootLayoutコンポーネントと子要素がレンダリングされる", () => {
    render(
      <RootLayout>
        <div>テスト子要素</div>
      </RootLayout>
    );
    expect(screen.getByText("テスト子要素")).toBeInTheDocument();
  });

  test("メタデータが正しく設定されている", () => {
    expect(metadata.title).toBe("Yamada Tetsuya Official");
    expect(metadata.description).toBe("Generated by create next app");
  });

  test("Headerコンポーネントがレンダリングされる", () => {
    render(
      <RootLayout>
        <div>テスト子要素</div>
      </RootLayout>
    );
    expect(screen.getByRole("banner")).toBeInTheDocument();
  });

  test("Footerコンポーネントがレンダリングされる", () => {
    render(
      <RootLayout>
        <div>テスト子要素</div>
      </RootLayout>
    );
    expect(screen.getByRole("contentinfo")).toBeInTheDocument();
  });
});
